name: Deploy Discord Bot

on:
  workflow_dispatch: # Permet de déclencher manuellement le workflow
  schedule:
    - cron: '0 * * * *' # Exécuter toutes les heures

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Stop previous bot instance if running
        run: |
          if [ -f bot.pid ]; then
            PID=$(cat bot.pid)
            if ps -p $PID > /dev/null; then
              echo "Stopping previous bot instance with PID $PID"
              kill $PID
            fi
            rm -f bot.pid
          fi

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          nohup python bot.py & echo $! > bot.pid

      - name: Schedule next run
        if: ${{ success() || failure() }}
        run: |
          echo "Scheduling next run..."
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy_bot.yml/dispatches \
            -d '{"ref":"main"}'
