name: Deploy Discord Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Stop previous bot instance
        run: |
          if [ -f /tmp/discord_bot.lock ]; then
            pid=$(cat /tmp/discord_bot.lock)
            if [ -d /proc/$pid ]; then
              echo "Stopping previous bot instance with PID $pid"
              kill -9 $pid
            fi
            rm -f /tmp/discord_bot.lock
          fi

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          nohup python bot.py & echo $! > /tmp/discord_bot.lock
